version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  back-tier:

services:

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always

  parking-api:
    image: parking-api:latest
    build:
      context: .
    volumes:
      - ./custom.properties:/tmp/application.properties
    ports:
      - 8080:8080
    networks:
      - back-tier
    restart: always

  parking-api-test:
    image: parkingtest:latest
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - parking-api
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
    restart: always
