{
 "title": "Parking API",
 "description": "Parking API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "APIs info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Latency Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(requests_latency_seconds_sum[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request per seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(requests_latency_seconds_count[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Parking Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Revenue per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "rate(parking_billing_amount_sum[1m])",
     "legendFormat": "Parking Type : {{spotType}}"
    }
   ]
  },
  {
   "title": "Parking Occupancy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "used_spots ", "legendFormat": "Used : {{spotType}}" },
    { "expr": "spot_total", "legendFormat": "Total : {{spotType}}" }
   ]
  },
  {
   "title": "Capacity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    { "expr": "used_spots/spot_total", "legendFormat": "{{spotType}}" }
   ]
  },
  { "title": "JVM overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU  Usage ( Process )",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$instance\"}",
     "legendFormat": "{{area}} memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\"}",
     "legendFormat": "current [{{instance}}]"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$instance\"}",
     "legendFormat": "daemon [{{instance}}]"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=~\"$instance\"}",
     "legendFormat": "loaded [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{instance=~\"$instance\"}",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  }
 ]
}